//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the roboservo_sample package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __roboservo_sample__ROBOSERVO_PARAMCONFIG_H__
#define __roboservo_sample__ROBOSERVO_PARAMCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace roboservo_sample
{
  class roboservo_paramConfigStatics;

  class roboservo_paramConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(roboservo_paramConfig &config, const roboservo_paramConfig &max, const roboservo_paramConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const roboservo_paramConfig &config1, const roboservo_paramConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, roboservo_paramConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const roboservo_paramConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, roboservo_paramConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const roboservo_paramConfig &config) const = 0;
      virtual void getValue(const roboservo_paramConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T roboservo_paramConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T roboservo_paramConfig::* field;

      virtual void clamp(roboservo_paramConfig &config, const roboservo_paramConfig &max, const roboservo_paramConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const roboservo_paramConfig &config1, const roboservo_paramConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, roboservo_paramConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const roboservo_paramConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, roboservo_paramConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const roboservo_paramConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const roboservo_paramConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, roboservo_paramConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, roboservo_paramConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<roboservo_paramConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(roboservo_paramConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("Joint_name"==(*_i)->name){Joint_name = boost::any_cast<std::string>(val);}
        if("Profile_velocity"==(*_i)->name){Profile_velocity = boost::any_cast<int>(val);}
        if("Profile_acceleration"==(*_i)->name){Profile_acceleration = boost::any_cast<int>(val);}
        if("Profile_deceleration"==(*_i)->name){Profile_deceleration = boost::any_cast<int>(val);}
      }
    }

    std::string Joint_name;
int Profile_velocity;
int Profile_acceleration;
int Profile_deceleration;

    bool state;
    std::string name;

    
}groups;



//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      std::string Joint_name;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Profile_velocity;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Profile_acceleration;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      int Profile_deceleration;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("roboservo_paramConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const roboservo_paramConfig &__max__ = __getMax__();
      const roboservo_paramConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const roboservo_paramConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const roboservo_paramConfig &__getDefault__();
    static const roboservo_paramConfig &__getMax__();
    static const roboservo_paramConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const roboservo_paramConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void roboservo_paramConfig::ParamDescription<std::string>::clamp(roboservo_paramConfig &config, const roboservo_paramConfig &max, const roboservo_paramConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class roboservo_paramConfigStatics
  {
    friend class roboservo_paramConfig;

    roboservo_paramConfigStatics()
    {
roboservo_paramConfig::GroupDescription<roboservo_paramConfig::DEFAULT, roboservo_paramConfig> Default("Default", "", 0, 0, true, &roboservo_paramConfig::groups);
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Joint_name = "roboservo_1";
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Joint_name = "roboservo_3";
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Joint_name = "roboservo_1";
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<std::string>("Joint_name", "str", 0, "A list of joints name", "{'enum_description': 'A list of nodes name', 'enum': [{'srcline': 10, 'description': 'The 1st joint', 'srcfile': '/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg', 'cconsttype': 'const char * const', 'value': 'roboservo_1', 'ctype': 'std::string', 'type': 'str', 'name': '1'}, {'srcline': 11, 'description': 'The 2nd joint', 'srcfile': '/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg', 'cconsttype': 'const char * const', 'value': 'roboservo_2', 'ctype': 'std::string', 'type': 'str', 'name': '2'}, {'srcline': 12, 'description': 'The 3rd joint', 'srcfile': '/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg', 'cconsttype': 'const char * const', 'value': 'roboservo_3', 'ctype': 'std::string', 'type': 'str', 'name': '3'}]}", &roboservo_paramConfig::Joint_name)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<std::string>("Joint_name", "str", 0, "A list of joints name", "{'enum_description': 'A list of nodes name', 'enum': [{'srcline': 10, 'description': 'The 1st joint', 'srcfile': '/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg', 'cconsttype': 'const char * const', 'value': 'roboservo_1', 'ctype': 'std::string', 'type': 'str', 'name': '1'}, {'srcline': 11, 'description': 'The 2nd joint', 'srcfile': '/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg', 'cconsttype': 'const char * const', 'value': 'roboservo_2', 'ctype': 'std::string', 'type': 'str', 'name': '2'}, {'srcline': 12, 'description': 'The 3rd joint', 'srcfile': '/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg', 'cconsttype': 'const char * const', 'value': 'roboservo_3', 'ctype': 'std::string', 'type': 'str', 'name': '3'}]}", &roboservo_paramConfig::Joint_name)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Profile_velocity = 1;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Profile_velocity = 6400;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Profile_velocity = 1000;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<int>("Profile_velocity", "int", 0, "Profile velocity", "", &roboservo_paramConfig::Profile_velocity)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<int>("Profile_velocity", "int", 0, "Profile velocity", "", &roboservo_paramConfig::Profile_velocity)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Profile_acceleration = 1;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Profile_acceleration = 30000;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Profile_acceleration = 1000;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<int>("Profile_acceleration", "int", 0, "Profile acceleration", "", &roboservo_paramConfig::Profile_acceleration)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<int>("Profile_acceleration", "int", 0, "Profile acceleration", "", &roboservo_paramConfig::Profile_acceleration)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __min__.Profile_deceleration = 1;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __max__.Profile_deceleration = 30000;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __default__.Profile_deceleration = 1000;
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.abstract_parameters.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<int>("Profile_deceleration", "int", 0, "Profile decceleration", "", &roboservo_paramConfig::Profile_deceleration)));
//#line 274 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __param_descriptions__.push_back(roboservo_paramConfig::AbstractParamDescriptionConstPtr(new roboservo_paramConfig::ParamDescription<int>("Profile_deceleration", "int", 0, "Profile decceleration", "", &roboservo_paramConfig::Profile_deceleration)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(roboservo_paramConfig::AbstractGroupDescriptionConstPtr(new roboservo_paramConfig::GroupDescription<roboservo_paramConfig::DEFAULT, roboservo_paramConfig>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<roboservo_paramConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<roboservo_paramConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<roboservo_paramConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    roboservo_paramConfig __max__;
    roboservo_paramConfig __min__;
    roboservo_paramConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const roboservo_paramConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static roboservo_paramConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &roboservo_paramConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const roboservo_paramConfig &roboservo_paramConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const roboservo_paramConfig &roboservo_paramConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const roboservo_paramConfig &roboservo_paramConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<roboservo_paramConfig::AbstractParamDescriptionConstPtr> &roboservo_paramConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<roboservo_paramConfig::AbstractGroupDescriptionConstPtr> &roboservo_paramConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const roboservo_paramConfigStatics *roboservo_paramConfig::__get_statics__()
  {
    const static roboservo_paramConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = roboservo_paramConfigStatics::get_instance();

    return statics;
  }

//#line 10 "/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg"
      const char * const roboservo_param_1 = "roboservo_1";
//#line 11 "/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg"
      const char * const roboservo_param_2 = "roboservo_2";
//#line 12 "/home/futaba/catkin_ws/src/roboservo_sample/cfg/roboservo_param.cfg"
      const char * const roboservo_param_3 = "roboservo_3";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ROBOSERVO_PARAMRECONFIGURATOR_H__
